version: "3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  redis:
    image: redis:7
    container_name: ecommerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - 8000:8000
    environment:
      APP_NAME: Ecommerce
      GRPC_PORT: 50051
      PORT: 8000
      MONGO_URL: mongodb+srv://cryptonfuturemedia1989_db_user:gPtmqIFk8JB2SVeI@cluster0.ejp9pmh.mongodb.net/
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}