name: Node CI/CD Local

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Packages
        shell: cmd
        run: npm install

      # - name: Run Tests
      #   shell: cmd
      #   run: npm test

      - name: Stop Containers
        shell: cmd
        run: docker compose down

      - name: Remove Unused Images
        shell: cmd
        run: docker image prune -f

      - name: Build & Start Containers
        shell: cmd
        run: docker compose up -d --build

      - name: Verify Containers
        shell: cmd
        run: docker ps

     