name: Node CI/CD Local

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        shell: bash
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Stop Containers
        run: docker compose down

      - name: Build & Start Containers
        run: docker compose up -d --build

      - name: Remove Unused Images
        run: docker image prune -f