name: Node CI/CD Local

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Packages
        shell: cmd
        run: npm install

      # - name: Run Tests
      #   shell: cmd
      #   run: npm test

      - name: Create .env
        shell: cmd
        run: |
          echo PORT=${{ secrets.PORT }}>>.env
          echo GRPC_PORT=${{ secrets.GRPC_PORT }}>>.env
          echo MONGO_URI=${{ secrets.MONGO_URI }}>>.env
          echo ACCESS_TOKEN_SECRET_KEY=${{ secrets.ACCESS_TOKEN_SECRET_KEY }}>>.env
          echo REFRESH_TOKEN_SECRET_KEY=${{ secrets.REFRESH_TOKEN_SECRET_KEY }}>>.env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }}>>.env
          echo REDIS_PORT=${{ secrets.REDIS_PORT }}>>.env

      - name: Stop Containers
        shell: cmd
        run: docker compose down

      - name: Remove Unused Images
        shell: cmd
        run: docker image prune -f

      - name: Build & Start Containers
        shell: cmd
        run: docker compose up -d --build

      - name: Verify Containers
        shell: cmd
        run: docker ps

     